mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import LoginView, LogoutView


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('accounts/logout/', LogoutView.as_view(), name='logout'),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

# urlpatterns = [
#     path('', views.index, name='index'),
#     path('<int:question_id>/', views.detail, name='detail'),
#     path('<int:question_id>/results/', views.results, name='results'),
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.VoteView.as_view(), name='vote'),
    path('name/<int:name_id>/', views.NameEditView.as_view(), name='name_edit'),
]

mysite/polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
import datetime


GENDER_CHOICE = (
    (0, "female"),
    (1, "male")
)


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date_published')
    # pub_date = models.DateTimeField('date_published', null=True)

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    # def was_published_recently(self):
    #     now = timezone.now()
    #     return now - datetime.timedelta(days=1) <= self.pub_date <= now
    #     # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class MyTestClass(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    choice_text_2 = models.CharField(max_length=200)
    votes_2 = models.IntegerField(default=0)


class Name(models.Model):
    who_add = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    gender = models.IntegerField(choices=GENDER_CHOICE)

    def __str__(self):
        return "{0} {1}".format(self.name, self.surname)

mysite/polls/forms.py
from django import forms
from .models import GENDER_CHOICE


class NameForm(forms.Form):
    name = forms.CharField(label='Your name', max_length=100)
    surname = forms.CharField(label='Your surname', max_length=100)
    gender = forms.ChoiceField(choices=GENDER_CHOICE, label='Gender')


class LoginForm(forms.Form):
    username = forms.CharField(label='Your name')
    password = forms.CharField(widget=forms.PasswordInput, label='Password')

mysite/polls/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.utils.decorators import method_decorator
from .forms import NameForm, LoginForm
from .models import Question, Choice, Name
from django.urls import reverse
from django.template import loader
from django.views import generic, View
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt


class IndexView(LoginRequiredMixin, View):
    def get(self, request):
        form = NameForm()
        questions = Question.objects.filter(
                    pub_date__lte=timezone.now()
                ).order_by('-pub_date')[:5]
        print(request.user)
        context = {
            'latest_question_list': questions,
            'form': form,
        }
        return render(request, 'polls/index.html', context)

    def post(self, request):

        form = NameForm(request.POST)
        if form.is_valid():
            question = Question.objects.get(pk="+1")
            # created_name = Name.objects.create(**form.cleaned_data)
            created_name = Name.objects.create(
                name=form.cleaned_data['name'],
                surname=form.cleaned_data['surname'],
                gender=form.cleaned_data['gender'],
                who_add=request.user,
                question=question,
            )
        else:
            context = {
                'message': "Your form is not valid. Sorry!",
            }
            return render(request, 'polls/index.html', context)

        form = NameForm()
        questions = Question.objects.filter(
                    pub_date__lte=timezone.now()
                )
        context = {
            'latest_question_list': questions,
            'form': form,
            'message': created_name,
        }
        return render(request, 'polls/index.html', context)


@method_decorator(csrf_exempt, name='dispatch')
class NameEditView(View):

    def get(self, request, name_id):
        selected_name = None
        name_url = 'name_edit'
        try:
            selected_name = Name.objects.get(pk=name_id)
            form = NameForm(initial={
                'name': selected_name.name,
                'surname': selected_name.surname,
                'gender': selected_name.gender,
            })
        except ObjectDoesNotExist:
            form = NameForm()
            messages.error(request, 'Document deleted.')
            return render(request, 'polls/error_page.html')
        context = {
            'selected_name': selected_name,
            'name_id': name_id,
            'form': form,
            'name_url': name_url,
        }
        return render(request, 'polls/name_edit.html', context)

    def post(self, request, name_id):

        selected_name = Name.objects.get(pk=name_id)
        form = NameForm(request.POST)
        print(form.is_valid())
        if form.is_valid():
            selected_name.name = form.cleaned_data["name"]
            selected_name.surname = form.cleaned_data["surname"]
            selected_name.gender = form.cleaned_data["gender"]
            selected_name.save()

        return HttpResponseRedirect(reverse('polls:name_edit', args=(name_id,)))

        # try:
        #     selected_name = Name.objects.get(pk=name_id)
        #     form = NameForm(request.POST)
        #     if form.is_valid():
        #         selected_name.name = form.cleaned_data["name"]
        #         selected_name.surname = form.cleaned_data["surname"]
        #         selected_name.gender = form.cleaned_data["gender"]
        #         selected_name.save()
        #     else:
        #         return render(request, 'polls/error_page.html')
        # except ObjectDoesNotExist:
        #     messages.error(request, 'Document deleted.')
        #     return render(request, 'polls/error_page.html')
        # return HttpResponseRedirect(reverse('polls:name_edit', args=(name_id,)))


class DetailView(PermissionRequiredMixin, View):
    permission_required = 'polls.view_question'
    raise_exception = True

    def get(self, request, pk):
        questions = Question.objects.filter(pub_date__lte=timezone.now())
        question = get_object_or_404(questions, pk=pk)
        context = {
            'question': question,
        }
        return render(request, 'polls/detail.html', context)


class ResultsView(View):
    def get(self, request, pk):
        question = get_object_or_404(Question, pk=pk)
        context = {
            'question': question,
        }
        return render(request, 'polls/results.html', context)


class VoteView(View):
    def get(self, request, question_id):
        return HttpResponseRedirect(reverse('polls:index'))

    def post(self, request, question_id):
        question = get_object_or_404(Question, pk=question_id)
        try:
            selected_choice = question.choice_set.get(pk=request.POST['choice'])
        except (KeyError, Choice.DoesNotExist):
            # Redisplay the question voting form.
            context = {
                'question': question,
                'error_message': "You didn't select a choice.",
            }
            return render(request, 'polls/detail.html', context)
        else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class LoginView(View):

    def get(self, request):
        ctx = {
            'form': LoginForm,
        }
        return render(request, 'login.html', ctx)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                url = request.GET.get('next')
                if url:
                    return redirect(url)
                return HttpResponseRedirect(reverse('polls:index'))
                # return HttpResponseRedirect('/polls/')

            form.add_error(field=None, error='Zły login lub hasło!')

        ctx = {
            'form': form,
        }
        return render(request, 'login.html', ctx)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('login'))


# class IndexView(generic.ListView):
#     template_name = 'polls/index.html'
#     context_object_name = 'latest_question_list'
#
#     def get_queryset(self):
#         # print(Choice.objects.all().query)
#         # questions_sorted = Question.objects.filter(
#         #     pub_date__lte=timezone.now()
#         # ).order_by('-pub_date')[:5]
#         # print(questions_sorted.query)
#         return Question.objects.filter(
#             pub_date__lte=timezone.now()
#         ).order_by('-pub_date')[:5]

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context = {
#         'question': question,
#     }
#     return render(request, 'polls/detail.html', context)
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     context = {
#         'question': question,
#     }
#     return render(request, 'polls/results.html', context)
#
#
# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choice_set.get(pk=request.POST['choice'])
#     except (KeyError, Choice.DoesNotExist):
#         # Redisplay the question voting form.
#         context = {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         }
#         return render(request, 'polls/detail.html', context)
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% if question.choice_set.all %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
    {% else %}
    Brak wyborów dla tego pytania.
    {% endif %}
</form>

</body>
</html>

mysite/polls/templates/polls/error_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <h2{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h2>
    {% endfor %}
</ul>
{% endif %}
<h2>Błędnie wypełniony formularz</h2>
</body>
</html>

mysite/polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


{% if message %}<p><strong>{{ message }}</strong></p>{% endif %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }} - {{ question.pub_date }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<form action="{% url 'polls:index' %}" method="post">
    {% csrf_token %}
    {{ form.as_p  }}
    <input type="submit" value="Submit">
</form>


<p>
<a href="{% url 'logout' %}">Logout</a>
</p>
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</body>
</html>

mysite/polls/templates/polls/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p  }}
    <input type="submit" value="Login">
</form>
</body>
</html>

mysite/polls/templates/polls/name_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!--<form action="{% url 'polls:name_edit' name_id %}" method="post">-->
<!--{% csrf_token %}-->
<!--    <tr><th><label for="id_name">Your name:</label></th><td><input type="text" name="surname" maxlength="100"-->
<!--                                                                   required id="id_name" value="{{ selected_name.name }}"></td></tr>-->
<!--    <tr><th><label for="id_surname">Your surname:</label></th><td><input type="text" name="surname" maxlength="100"-->
<!--                                                                         required id="id_surname" value="{{ selected_name.surname }}"></td></tr>-->
<!--    <input type="submit" value="Submit">-->
<!--</form>-->


<form action="{% url 'polls:name_edit' name_id %}" method="post">
    {% csrf_token %}
    {{ form  }}
    <input type="submit" value="Submit">

</form>
</body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>